_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_p67_res2net_fpn_backbone"
  WEIGHTS: "models/r2_101.pkl"
  RESNETS:
    DEPTH: 101
    WIDTH_PER_GROUP: 26
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  CENTERNET:
    USE_DEFORMABLE: True
    NUM_CLASSES: 111
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4"]
    NUM_CLASSES: 111
INPUT:
  FORMAT: RGB
TEST:
  EVAL_PERIOD: 1000
SOLVER:
  MAX_ITER: 24000
  CHECKPOINT_PERIOD: 4000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.04
  IMS_PER_BATCH: 32
INPUT:
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 896
DATASETS:
  TRAIN: ("xary_coco_data",)
  TEST: ("xary_coco_data_val",)