_BASE_: "Base-CenterNet2.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 111
  CENTERNET:
    NUM_CLASSES: 111
DATASETS:
  TRAIN: ("xary_coco_data",)
  TEST: ("xary_coco_data_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (8000, 10000)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 2000
  WARMUP_ITERS: 2000
  WARMUP_FACTOR: 0.00025
  CLIP_GRADIENTS:
    ENABLED: True