_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_p37_fcos_dla_bifpn_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  CENTERNET:
    POST_NMS_TOPK_TEST: 128
    NUM_CLASSES: 111
  ROI_HEADS:
    NUM_CLASSES: 111
  WEIGHTS: ''
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.04
  STEPS: (20000, 22400)
  MAX_ITER: 24000
  CHECKPOINT_PERIOD: 4000
  WARMUP_ITERS: 4000
  WARMUP_FACTOR: 0.00025
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 900
DATASETS:
  TRAIN: ("xary_coco_data",)
  TEST: ("xary_coco_data_val",)
