_BASE_: "Base-CenterNet2.yaml"
MODEL:
  WEIGHTS: "models/CenterNet2_DLA-BiFPN-P3_4x.pth"
  BACKBONE:
    NAME: "build_p35_fcos_dla_bifpn_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 3
    NUM_BIFPN: 4
  DLA:
    NUM_LAYERS: 34
    NORM: "SyncBN"  #多gpu下才使用syncbn
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4", "p5"]
    NUM_CLASSES: 111
  CENTERNET:
    POST_NMS_TOPK_TEST: 128
    NUM_CLASSES: 111
    FPN_STRIDES: [8, 16, 32]
    IN_FEATURES: ['p3', 'p4', 'p5']
    SOI: [[0, 64], [48, 192], [128, 1000000]]
DATASETS:
  TRAIN: ("xary_coco_data",)
  TEST: ("xary_coco_data_val",)
SOLVER:
  RESET_ITER: True
  IMS_PER_BATCH: 64
  BASE_LR: 0.04
  STEPS: (10000, 11200)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 2000
  WARMUP_ITERS: 2000
  WARMUP_FACTOR: 0.00025
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 900
  MAX_SIZE_TEST: 736
  MIN_SIZE_TEST: 512